// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "princessd":return img`
........................
........................
........5.55.5..........
........535535..........
........555555..........
........ffffff..........
.......feeeeeef.........
......feeeeeeeef........
......feeffffeef........
......feffddffef........
.....fefdfddfdfef.......
.....fefd3dd3dfef.......
.....feefddddfeef.......
....feef3ffff3feef......
.....ffd353353dff.......
.....fddf3553fddf.......
......ff333333ff........
......f33333333f........
......ffffffffff........
........ff..ff..........
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
